# This is an example configuration file
# To learn more, see the full config.yaml reference: https://docs.continue.dev/reference

name: Example Config
version: 1.0.0
schema: v1

# Define which models can be used
# https://docs.continue.dev/customization/models
models:
  - name: Claude Opus
    provider: openai
    model: anthropic/claude-opus-4.6
    apiBase: https://openrouter.ai/api/v1
    apiKey: YOUR_OPENROUTER_API_KEY
  - name: Claude Sonnet
    provider: openai
    model: anthropic/claude-sonnet-4.5
    apiBase: https://openrouter.ai/api/v1
    apiKey: YOUR_OPENROUTER_API_KEY

# MCP Servers that Continue can access
# https://docs.continue.dev/customization/mcp-tools
mcpServers:
  - uses: anthropic/memory-mcp
