# This is an example configuration file
# To learn more, see the full config.yaml reference: https://docs.continue.dev/reference

name: Example Config
version: 1.0.0
schema: v1

# Define which models can be used
# https://docs.continue.dev/customization/models
models:
  - name: Claude Opus
    provider: openai
    model: anthropic/claude-opus-4.6
    apiBase: https://openrouter.ai/api/v1
    apiKey: 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
  - name: Claude Sonnet
    provider: openai
    model: anthropic/claude-sonnet-4.5
    apiBase: https://openrouter.ai/api/v1
    apiKey: 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

# MCP Servers that Continue can access
# https://docs.continue.dev/customization/mcp-tools
mcpServers:
  - uses: anthropic/memory-mcp
